apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: petclinic-route
spec:
  parentRefs:
  - name: petclinic-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: petclinic
      port: 80
